name: .NET CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

concurrency:
  group: dotnet-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Cache NuGet
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore (solution)
        run: dotnet restore OtodomParser.sln

      - name: Build (Release)
        run: dotnet build OtodomParser.sln --configuration Release --no-restore

  test:
    name: Test - ${{ matrix.name }}
    runs-on: ubuntu-latest
    needs: build

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Application.Tests
            path: Tests/Application.Tests/Application.Tests.csproj
            artifact: application-tests-results
          - name: Infrastructure.Tests
            path: Tests/Infrastructure.Tests/Infrastructure.Tests.csproj
            artifact: infrastructure-tests-results

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Cache NuGet
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore (solution)
        run: dotnet restore OtodomParser.sln

      - name: Test (Release)
        run: dotnet test ${{ matrix.path }} --configuration Release --no-restore --logger "trx;LogFileName=TestResults.trx"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: "**/TestResults.trx"